version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: condominio_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: condominio_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - ./database/create_mysql.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/mysql
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: condominio_backend
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8000:80"
    environment:
      - DB_TYPE=mysql
      - DB_HOST=db
      - DB_NAME=condominio_db
      - DB_USER=user
      - DB_PASS=password
    volumes:
      - ./backend:/var/www/html/backend
      - ./config:/var/www/html/config
      - ./database:/var/www/html/database
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: condominio_frontend
    restart: unless-stopped
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
